#!/bin/bash

# Global Template CRUD 驗證腳本

FRONTEND_URL="http://localhost:3000"
TEMPLATES_PAGE="${FRONTEND_URL}/#/admin/templates"

echo "🧪 Global Template CRUD 功能驗證"
echo "================================"
echo ""

# 檢查服務狀態
echo "1️⃣  檢查服務狀態..."
FRONTEND_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$FRONTEND_URL")

if [ "$FRONTEND_STATUS" = "200" ]; then
  echo "  ✅ Frontend 運行中 ($FRONTEND_STATUS)"
else
  echo "  ❌ Frontend 無法訪問 ($FRONTEND_STATUS)"
  echo "  請確保 frontend server 正在運行: cd Frontend && npm run dev"
  exit 1
fi

echo ""
echo "2️⃣  檢查頁面可訪問性..."
echo "  📄 Templates 頁面: $TEMPLATES_PAGE"
echo ""
echo "3️⃣  功能檢查清單："
echo ""
echo "  請在瀏覽器中訪問: $TEMPLATES_PAGE"
echo ""
echo "  ✅ 檢查項目："
echo "    1. 頁面是否正常載入"
echo "    2. 是否顯示 'New Global Template' 按鈕"
echo "    3. 點擊按鈕是否打開 modal"
echo "    4. Modal 中是否有以下欄位："
echo "       - Template Name"
echo "       - Description"
echo "       - Variables (可以添加/移除)"
echo "       - JSON Structure"
echo "    5. 填寫表單並點擊 'Save Template' 是否成功"
echo "    6. 列表中是否顯示新創建的 template"
echo "    7. 點擊 Edit 圖標是否打開編輯 modal"
echo "    8. 點擊 Delete 圖標是否成功刪除"
echo ""
echo "4️⃣  測試步驟："
echo ""
echo "  Step 1: 打開頁面"
echo "    $TEMPLATES_PAGE"
echo ""
echo "  Step 2: 創建 Global Template"
echo "    - 點擊 'New Global Template'"
echo "    - 填寫："
echo "      Name: Test Global Template"
echo "      Description: Automated test"
echo "      Variables: title, message"
echo "      JSON:"
echo "        {"
echo "          \"type\": \"AdaptiveCard\","
echo "          \"version\": \"1.4\","
echo "          \"body\": ["
echo "            {\"type\": \"TextBlock\", \"text\": \"{{title}}\"},"
echo "            {\"type\": \"TextBlock\", \"text\": \"{{message}}\"}"
echo "          ]"
echo "        }"
echo "    - 點擊 'Save Template'"
echo ""
echo "  Step 3: 驗證創建"
echo "    - 檢查列表中是否出現 'Test Global Template'"
echo "    - 檢查變數是否正確顯示"
echo ""
echo "  Step 4: 測試編輯"
echo "    - 點擊 Edit 圖標"
echo "    - 修改名稱或描述"
echo "    - 點擊 'Save Template'"
echo "    - 檢查是否更新成功"
echo ""
echo "  Step 5: 測試刪除"
echo "    - 點擊 Delete 圖標"
echo "    - 確認刪除"
echo "    - 檢查是否從列表中移除"
echo ""
echo "5️⃣  檢查 Console 錯誤："
echo "    - 打開開發者工具 (F12)"
echo "    - 查看 Console 標籤"
echo "    - 確認沒有錯誤訊息"
echo ""
echo "6️⃣  檢查 Network 請求："
echo "    - 打開開發者工具 Network 標籤"
echo "    - 執行操作時檢查是否有 API 請求"
echo "    - 目前應該使用 mock API（因為 backend 還沒有 global templates endpoint）"
echo ""
echo "================================"
echo "✅ 驗證腳本完成"
echo ""
echo "如果遇到問題，請檢查："
echo "  1. Frontend server 是否正常運行"
echo "  2. 瀏覽器 Console 是否有錯誤"
echo "  3. Network 標籤中的請求狀態"
