/*
Teams Notification API (Go implementation)

This specification documents the REST endpoints implemented in the Teams Notification Go service. Includes all available routes for internal and external APIs.  ## API Structure - **External APIs** (`/api/v1`): Public APIs for external clients - **Internal APIs** (`/internal/v1`): Internal management APIs - **System APIs**: Health, metrics, and configuration endpoints  ## Recent Updates (v1.0.0) - **Unified Configuration**: Environment-based configuration system - **Error Handling**: Standardized error responses with proper HTTP status codes - **Token Management**: Redis-backed token caching for improved performance - **Monitoring**: Enhanced health checks and system metrics - **Logging**: Structured logging with configurable levels and formats 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package teamsnotify

import (
	"encoding/json"
)

// checks if the PerformanceMetricsResponseCpu type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PerformanceMetricsResponseCpu{}

// PerformanceMetricsResponseCpu struct for PerformanceMetricsResponseCpu
type PerformanceMetricsResponseCpu struct {
	Usage *float32 `json:"usage,omitempty"`
	Cores *int32 `json:"cores,omitempty"`
}

// NewPerformanceMetricsResponseCpu instantiates a new PerformanceMetricsResponseCpu object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPerformanceMetricsResponseCpu() *PerformanceMetricsResponseCpu {
	this := PerformanceMetricsResponseCpu{}
	return &this
}

// NewPerformanceMetricsResponseCpuWithDefaults instantiates a new PerformanceMetricsResponseCpu object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPerformanceMetricsResponseCpuWithDefaults() *PerformanceMetricsResponseCpu {
	this := PerformanceMetricsResponseCpu{}
	return &this
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (o *PerformanceMetricsResponseCpu) GetUsage() float32 {
	if o == nil || IsNil(o.Usage) {
		var ret float32
		return ret
	}
	return *o.Usage
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PerformanceMetricsResponseCpu) GetUsageOk() (*float32, bool) {
	if o == nil || IsNil(o.Usage) {
		return nil, false
	}
	return o.Usage, true
}

// HasUsage returns a boolean if a field has been set.
func (o *PerformanceMetricsResponseCpu) HasUsage() bool {
	if o != nil && !IsNil(o.Usage) {
		return true
	}

	return false
}

// SetUsage gets a reference to the given float32 and assigns it to the Usage field.
func (o *PerformanceMetricsResponseCpu) SetUsage(v float32) {
	o.Usage = &v
}

// GetCores returns the Cores field value if set, zero value otherwise.
func (o *PerformanceMetricsResponseCpu) GetCores() int32 {
	if o == nil || IsNil(o.Cores) {
		var ret int32
		return ret
	}
	return *o.Cores
}

// GetCoresOk returns a tuple with the Cores field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PerformanceMetricsResponseCpu) GetCoresOk() (*int32, bool) {
	if o == nil || IsNil(o.Cores) {
		return nil, false
	}
	return o.Cores, true
}

// HasCores returns a boolean if a field has been set.
func (o *PerformanceMetricsResponseCpu) HasCores() bool {
	if o != nil && !IsNil(o.Cores) {
		return true
	}

	return false
}

// SetCores gets a reference to the given int32 and assigns it to the Cores field.
func (o *PerformanceMetricsResponseCpu) SetCores(v int32) {
	o.Cores = &v
}

func (o PerformanceMetricsResponseCpu) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PerformanceMetricsResponseCpu) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Usage) {
		toSerialize["usage"] = o.Usage
	}
	if !IsNil(o.Cores) {
		toSerialize["cores"] = o.Cores
	}
	return toSerialize, nil
}

type NullablePerformanceMetricsResponseCpu struct {
	value *PerformanceMetricsResponseCpu
	isSet bool
}

func (v NullablePerformanceMetricsResponseCpu) Get() *PerformanceMetricsResponseCpu {
	return v.value
}

func (v *NullablePerformanceMetricsResponseCpu) Set(val *PerformanceMetricsResponseCpu) {
	v.value = val
	v.isSet = true
}

func (v NullablePerformanceMetricsResponseCpu) IsSet() bool {
	return v.isSet
}

func (v *NullablePerformanceMetricsResponseCpu) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePerformanceMetricsResponseCpu(val *PerformanceMetricsResponseCpu) *NullablePerformanceMetricsResponseCpu {
	return &NullablePerformanceMetricsResponseCpu{value: val, isSet: true}
}

func (v NullablePerformanceMetricsResponseCpu) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePerformanceMetricsResponseCpu) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


