/*
Teams Notification API (Go implementation)

This specification documents the REST endpoints implemented in the Teams Notification Go service. Includes all available routes for internal and external APIs.  ## API Structure - **External APIs** (`/api/v1`): Public APIs for external clients - **Internal APIs** (`/internal/v1`): Internal management APIs - **System APIs**: Health, metrics, and configuration endpoints  ## Recent Updates (v1.0.0) - **Unified Configuration**: Environment-based configuration system - **Error Handling**: Standardized error responses with proper HTTP status codes - **Token Management**: Redis-backed token caching for improved performance - **Monitoring**: Enhanced health checks and system metrics - **Logging**: Structured logging with configurable levels and formats 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package teamsnotify

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BotCapabilitiesUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BotCapabilitiesUpdateRequest{}

// BotCapabilitiesUpdateRequest struct for BotCapabilitiesUpdateRequest
type BotCapabilitiesUpdateRequest struct {
	Capabilities []string `json:"capabilities"`
}

type _BotCapabilitiesUpdateRequest BotCapabilitiesUpdateRequest

// NewBotCapabilitiesUpdateRequest instantiates a new BotCapabilitiesUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBotCapabilitiesUpdateRequest(capabilities []string) *BotCapabilitiesUpdateRequest {
	this := BotCapabilitiesUpdateRequest{}
	this.Capabilities = capabilities
	return &this
}

// NewBotCapabilitiesUpdateRequestWithDefaults instantiates a new BotCapabilitiesUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBotCapabilitiesUpdateRequestWithDefaults() *BotCapabilitiesUpdateRequest {
	this := BotCapabilitiesUpdateRequest{}
	return &this
}

// GetCapabilities returns the Capabilities field value
func (o *BotCapabilitiesUpdateRequest) GetCapabilities() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value
// and a boolean to check if the value has been set.
func (o *BotCapabilitiesUpdateRequest) GetCapabilitiesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Capabilities, true
}

// SetCapabilities sets field value
func (o *BotCapabilitiesUpdateRequest) SetCapabilities(v []string) {
	o.Capabilities = v
}

func (o BotCapabilitiesUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BotCapabilitiesUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["capabilities"] = o.Capabilities
	return toSerialize, nil
}

func (o *BotCapabilitiesUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"capabilities",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBotCapabilitiesUpdateRequest := _BotCapabilitiesUpdateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBotCapabilitiesUpdateRequest)

	if err != nil {
		return err
	}

	*o = BotCapabilitiesUpdateRequest(varBotCapabilitiesUpdateRequest)

	return err
}

type NullableBotCapabilitiesUpdateRequest struct {
	value *BotCapabilitiesUpdateRequest
	isSet bool
}

func (v NullableBotCapabilitiesUpdateRequest) Get() *BotCapabilitiesUpdateRequest {
	return v.value
}

func (v *NullableBotCapabilitiesUpdateRequest) Set(val *BotCapabilitiesUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBotCapabilitiesUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBotCapabilitiesUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBotCapabilitiesUpdateRequest(val *BotCapabilitiesUpdateRequest) *NullableBotCapabilitiesUpdateRequest {
	return &NullableBotCapabilitiesUpdateRequest{value: val, isSet: true}
}

func (v NullableBotCapabilitiesUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBotCapabilitiesUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


