/*
Teams Notification API (Go implementation)

This specification documents the REST endpoints implemented in the Teams Notification Go service. Includes all available routes for internal and external APIs.  ## API Structure - **External APIs** (`/api/v1`): Public APIs for external clients - **Internal APIs** (`/internal/v1`): Internal management APIs - **System APIs**: Health, metrics, and configuration endpoints  ## Recent Updates (v1.0.0) - **Unified Configuration**: Environment-based configuration system - **Error Handling**: Standardized error responses with proper HTTP status codes - **Token Management**: Redis-backed token caching for improved performance - **Monitoring**: Enhanced health checks and system metrics - **Logging**: Structured logging with configurable levels and formats 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package teamsnotify

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DestinationTargetsUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DestinationTargetsUpdateRequest{}

// DestinationTargetsUpdateRequest struct for DestinationTargetsUpdateRequest
type DestinationTargetsUpdateRequest struct {
	Targets []DestinationTarget `json:"targets"`
}

type _DestinationTargetsUpdateRequest DestinationTargetsUpdateRequest

// NewDestinationTargetsUpdateRequest instantiates a new DestinationTargetsUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDestinationTargetsUpdateRequest(targets []DestinationTarget) *DestinationTargetsUpdateRequest {
	this := DestinationTargetsUpdateRequest{}
	this.Targets = targets
	return &this
}

// NewDestinationTargetsUpdateRequestWithDefaults instantiates a new DestinationTargetsUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDestinationTargetsUpdateRequestWithDefaults() *DestinationTargetsUpdateRequest {
	this := DestinationTargetsUpdateRequest{}
	return &this
}

// GetTargets returns the Targets field value
func (o *DestinationTargetsUpdateRequest) GetTargets() []DestinationTarget {
	if o == nil {
		var ret []DestinationTarget
		return ret
	}

	return o.Targets
}

// GetTargetsOk returns a tuple with the Targets field value
// and a boolean to check if the value has been set.
func (o *DestinationTargetsUpdateRequest) GetTargetsOk() ([]DestinationTarget, bool) {
	if o == nil {
		return nil, false
	}
	return o.Targets, true
}

// SetTargets sets field value
func (o *DestinationTargetsUpdateRequest) SetTargets(v []DestinationTarget) {
	o.Targets = v
}

func (o DestinationTargetsUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DestinationTargetsUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["targets"] = o.Targets
	return toSerialize, nil
}

func (o *DestinationTargetsUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"targets",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDestinationTargetsUpdateRequest := _DestinationTargetsUpdateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDestinationTargetsUpdateRequest)

	if err != nil {
		return err
	}

	*o = DestinationTargetsUpdateRequest(varDestinationTargetsUpdateRequest)

	return err
}

type NullableDestinationTargetsUpdateRequest struct {
	value *DestinationTargetsUpdateRequest
	isSet bool
}

func (v NullableDestinationTargetsUpdateRequest) Get() *DestinationTargetsUpdateRequest {
	return v.value
}

func (v *NullableDestinationTargetsUpdateRequest) Set(val *DestinationTargetsUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDestinationTargetsUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDestinationTargetsUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDestinationTargetsUpdateRequest(val *DestinationTargetsUpdateRequest) *NullableDestinationTargetsUpdateRequest {
	return &NullableDestinationTargetsUpdateRequest{value: val, isSet: true}
}

func (v NullableDestinationTargetsUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDestinationTargetsUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


