/*
Teams Notification API (Go implementation)

This specification documents the REST endpoints implemented in the Teams Notification Go service. Includes all available routes for internal and external APIs.  ## API Structure - **External APIs** (`/api/v1`): Public APIs for external clients - **Internal APIs** (`/internal/v1`): Internal management APIs - **System APIs**: Health, metrics, and configuration endpoints  ## Recent Updates (v1.0.0) - **Unified Configuration**: Environment-based configuration system - **Error Handling**: Standardized error responses with proper HTTP status codes - **Token Management**: Redis-backed token caching for improved performance - **Monitoring**: Enhanced health checks and system metrics - **Logging**: Structured logging with configurable levels and formats 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package teamsnotify

import (
	"encoding/json"
)

// checks if the PerformanceMetricsResponseRedis type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PerformanceMetricsResponseRedis{}

// PerformanceMetricsResponseRedis struct for PerformanceMetricsResponseRedis
type PerformanceMetricsResponseRedis struct {
	Memory *int32 `json:"memory,omitempty"`
	Keys *int32 `json:"keys,omitempty"`
	HitRate *float32 `json:"hitRate,omitempty"`
}

// NewPerformanceMetricsResponseRedis instantiates a new PerformanceMetricsResponseRedis object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPerformanceMetricsResponseRedis() *PerformanceMetricsResponseRedis {
	this := PerformanceMetricsResponseRedis{}
	return &this
}

// NewPerformanceMetricsResponseRedisWithDefaults instantiates a new PerformanceMetricsResponseRedis object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPerformanceMetricsResponseRedisWithDefaults() *PerformanceMetricsResponseRedis {
	this := PerformanceMetricsResponseRedis{}
	return &this
}

// GetMemory returns the Memory field value if set, zero value otherwise.
func (o *PerformanceMetricsResponseRedis) GetMemory() int32 {
	if o == nil || IsNil(o.Memory) {
		var ret int32
		return ret
	}
	return *o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PerformanceMetricsResponseRedis) GetMemoryOk() (*int32, bool) {
	if o == nil || IsNil(o.Memory) {
		return nil, false
	}
	return o.Memory, true
}

// HasMemory returns a boolean if a field has been set.
func (o *PerformanceMetricsResponseRedis) HasMemory() bool {
	if o != nil && !IsNil(o.Memory) {
		return true
	}

	return false
}

// SetMemory gets a reference to the given int32 and assigns it to the Memory field.
func (o *PerformanceMetricsResponseRedis) SetMemory(v int32) {
	o.Memory = &v
}

// GetKeys returns the Keys field value if set, zero value otherwise.
func (o *PerformanceMetricsResponseRedis) GetKeys() int32 {
	if o == nil || IsNil(o.Keys) {
		var ret int32
		return ret
	}
	return *o.Keys
}

// GetKeysOk returns a tuple with the Keys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PerformanceMetricsResponseRedis) GetKeysOk() (*int32, bool) {
	if o == nil || IsNil(o.Keys) {
		return nil, false
	}
	return o.Keys, true
}

// HasKeys returns a boolean if a field has been set.
func (o *PerformanceMetricsResponseRedis) HasKeys() bool {
	if o != nil && !IsNil(o.Keys) {
		return true
	}

	return false
}

// SetKeys gets a reference to the given int32 and assigns it to the Keys field.
func (o *PerformanceMetricsResponseRedis) SetKeys(v int32) {
	o.Keys = &v
}

// GetHitRate returns the HitRate field value if set, zero value otherwise.
func (o *PerformanceMetricsResponseRedis) GetHitRate() float32 {
	if o == nil || IsNil(o.HitRate) {
		var ret float32
		return ret
	}
	return *o.HitRate
}

// GetHitRateOk returns a tuple with the HitRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PerformanceMetricsResponseRedis) GetHitRateOk() (*float32, bool) {
	if o == nil || IsNil(o.HitRate) {
		return nil, false
	}
	return o.HitRate, true
}

// HasHitRate returns a boolean if a field has been set.
func (o *PerformanceMetricsResponseRedis) HasHitRate() bool {
	if o != nil && !IsNil(o.HitRate) {
		return true
	}

	return false
}

// SetHitRate gets a reference to the given float32 and assigns it to the HitRate field.
func (o *PerformanceMetricsResponseRedis) SetHitRate(v float32) {
	o.HitRate = &v
}

func (o PerformanceMetricsResponseRedis) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PerformanceMetricsResponseRedis) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Memory) {
		toSerialize["memory"] = o.Memory
	}
	if !IsNil(o.Keys) {
		toSerialize["keys"] = o.Keys
	}
	if !IsNil(o.HitRate) {
		toSerialize["hitRate"] = o.HitRate
	}
	return toSerialize, nil
}

type NullablePerformanceMetricsResponseRedis struct {
	value *PerformanceMetricsResponseRedis
	isSet bool
}

func (v NullablePerformanceMetricsResponseRedis) Get() *PerformanceMetricsResponseRedis {
	return v.value
}

func (v *NullablePerformanceMetricsResponseRedis) Set(val *PerformanceMetricsResponseRedis) {
	v.value = val
	v.isSet = true
}

func (v NullablePerformanceMetricsResponseRedis) IsSet() bool {
	return v.isSet
}

func (v *NullablePerformanceMetricsResponseRedis) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePerformanceMetricsResponseRedis(val *PerformanceMetricsResponseRedis) *NullablePerformanceMetricsResponseRedis {
	return &NullablePerformanceMetricsResponseRedis{value: val, isSet: true}
}

func (v NullablePerformanceMetricsResponseRedis) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePerformanceMetricsResponseRedis) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


