/*
Teams Notification API (Go implementation)

This specification documents the REST endpoints implemented in the Teams Notification Go service. Includes all available routes for internal and external APIs.  ## API Structure - **External APIs** (`/api/v1`): Public APIs for external clients - **Internal APIs** (`/internal/v1`): Internal management APIs - **System APIs**: Health, metrics, and configuration endpoints  ## Recent Updates (v1.0.0) - **Unified Configuration**: Environment-based configuration system - **Error Handling**: Standardized error responses with proper HTTP status codes - **Token Management**: Redis-backed token caching for improved performance - **Monitoring**: Enhanced health checks and system metrics - **Logging**: Structured logging with configurable levels and formats 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package teamsnotify

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DestinationCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DestinationCreateRequest{}

// DestinationCreateRequest struct for DestinationCreateRequest
type DestinationCreateRequest struct {
	// Project ID
	ProjectId string `json:"projectId"`
	// Bot ID
	BotId string `json:"botId"`
	// Destination type
	Type string `json:"type"`
	// List of targets
	Targets []DestinationTarget `json:"targets"`
	// Destination status
	Status *string `json:"status,omitempty"`
}

type _DestinationCreateRequest DestinationCreateRequest

// NewDestinationCreateRequest instantiates a new DestinationCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDestinationCreateRequest(projectId string, botId string, type_ string, targets []DestinationTarget) *DestinationCreateRequest {
	this := DestinationCreateRequest{}
	this.ProjectId = projectId
	this.BotId = botId
	this.Type = type_
	this.Targets = targets
	var status string = "active"
	this.Status = &status
	return &this
}

// NewDestinationCreateRequestWithDefaults instantiates a new DestinationCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDestinationCreateRequestWithDefaults() *DestinationCreateRequest {
	this := DestinationCreateRequest{}
	var status string = "active"
	this.Status = &status
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *DestinationCreateRequest) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *DestinationCreateRequest) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *DestinationCreateRequest) SetProjectId(v string) {
	o.ProjectId = v
}

// GetBotId returns the BotId field value
func (o *DestinationCreateRequest) GetBotId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BotId
}

// GetBotIdOk returns a tuple with the BotId field value
// and a boolean to check if the value has been set.
func (o *DestinationCreateRequest) GetBotIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BotId, true
}

// SetBotId sets field value
func (o *DestinationCreateRequest) SetBotId(v string) {
	o.BotId = v
}

// GetType returns the Type field value
func (o *DestinationCreateRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DestinationCreateRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DestinationCreateRequest) SetType(v string) {
	o.Type = v
}

// GetTargets returns the Targets field value
func (o *DestinationCreateRequest) GetTargets() []DestinationTarget {
	if o == nil {
		var ret []DestinationTarget
		return ret
	}

	return o.Targets
}

// GetTargetsOk returns a tuple with the Targets field value
// and a boolean to check if the value has been set.
func (o *DestinationCreateRequest) GetTargetsOk() ([]DestinationTarget, bool) {
	if o == nil {
		return nil, false
	}
	return o.Targets, true
}

// SetTargets sets field value
func (o *DestinationCreateRequest) SetTargets(v []DestinationTarget) {
	o.Targets = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DestinationCreateRequest) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DestinationCreateRequest) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DestinationCreateRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *DestinationCreateRequest) SetStatus(v string) {
	o.Status = &v
}

func (o DestinationCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DestinationCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["projectId"] = o.ProjectId
	toSerialize["botId"] = o.BotId
	toSerialize["type"] = o.Type
	toSerialize["targets"] = o.Targets
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

func (o *DestinationCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"projectId",
		"botId",
		"type",
		"targets",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDestinationCreateRequest := _DestinationCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDestinationCreateRequest)

	if err != nil {
		return err
	}

	*o = DestinationCreateRequest(varDestinationCreateRequest)

	return err
}

type NullableDestinationCreateRequest struct {
	value *DestinationCreateRequest
	isSet bool
}

func (v NullableDestinationCreateRequest) Get() *DestinationCreateRequest {
	return v.value
}

func (v *NullableDestinationCreateRequest) Set(val *DestinationCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDestinationCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDestinationCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDestinationCreateRequest(val *DestinationCreateRequest) *NullableDestinationCreateRequest {
	return &NullableDestinationCreateRequest{value: val, isSet: true}
}

func (v NullableDestinationCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDestinationCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


