/*
Teams Notification API (Go implementation)

This specification documents the REST endpoints implemented in the Teams Notification Go service. Includes all available routes for internal and external APIs.  ## API Structure - **External APIs** (`/api/v1`): Public APIs for external clients - **Internal APIs** (`/internal/v1`): Internal management APIs - **System APIs**: Health, metrics, and configuration endpoints  ## Recent Updates (v1.0.0) - **Unified Configuration**: Environment-based configuration system - **Error Handling**: Standardized error responses with proper HTTP status codes - **Token Management**: Redis-backed token caching for improved performance - **Monitoring**: Enhanced health checks and system metrics - **Logging**: Structured logging with configurable levels and formats 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package teamsnotify

import (
	"encoding/json"
	"time"
)

// checks if the QueueStatsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueueStatsResponse{}

// QueueStatsResponse struct for QueueStatsResponse
type QueueStatsResponse struct {
	Timestamp *time.Time `json:"timestamp,omitempty"`
	TotalItems *int32 `json:"totalItems,omitempty"`
	PendingItems *int32 `json:"pendingItems,omitempty"`
	ProcessingItems *int32 `json:"processingItems,omitempty"`
	CompletedItems *int32 `json:"completedItems,omitempty"`
	FailedItems *int32 `json:"failedItems,omitempty"`
	AverageProcessingTime *float32 `json:"averageProcessingTime,omitempty"`
	Throughput *float32 `json:"throughput,omitempty"`
}

// NewQueueStatsResponse instantiates a new QueueStatsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueueStatsResponse() *QueueStatsResponse {
	this := QueueStatsResponse{}
	return &this
}

// NewQueueStatsResponseWithDefaults instantiates a new QueueStatsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueueStatsResponseWithDefaults() *QueueStatsResponse {
	this := QueueStatsResponse{}
	return &this
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *QueueStatsResponse) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueStatsResponse) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *QueueStatsResponse) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *QueueStatsResponse) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

// GetTotalItems returns the TotalItems field value if set, zero value otherwise.
func (o *QueueStatsResponse) GetTotalItems() int32 {
	if o == nil || IsNil(o.TotalItems) {
		var ret int32
		return ret
	}
	return *o.TotalItems
}

// GetTotalItemsOk returns a tuple with the TotalItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueStatsResponse) GetTotalItemsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalItems) {
		return nil, false
	}
	return o.TotalItems, true
}

// HasTotalItems returns a boolean if a field has been set.
func (o *QueueStatsResponse) HasTotalItems() bool {
	if o != nil && !IsNil(o.TotalItems) {
		return true
	}

	return false
}

// SetTotalItems gets a reference to the given int32 and assigns it to the TotalItems field.
func (o *QueueStatsResponse) SetTotalItems(v int32) {
	o.TotalItems = &v
}

// GetPendingItems returns the PendingItems field value if set, zero value otherwise.
func (o *QueueStatsResponse) GetPendingItems() int32 {
	if o == nil || IsNil(o.PendingItems) {
		var ret int32
		return ret
	}
	return *o.PendingItems
}

// GetPendingItemsOk returns a tuple with the PendingItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueStatsResponse) GetPendingItemsOk() (*int32, bool) {
	if o == nil || IsNil(o.PendingItems) {
		return nil, false
	}
	return o.PendingItems, true
}

// HasPendingItems returns a boolean if a field has been set.
func (o *QueueStatsResponse) HasPendingItems() bool {
	if o != nil && !IsNil(o.PendingItems) {
		return true
	}

	return false
}

// SetPendingItems gets a reference to the given int32 and assigns it to the PendingItems field.
func (o *QueueStatsResponse) SetPendingItems(v int32) {
	o.PendingItems = &v
}

// GetProcessingItems returns the ProcessingItems field value if set, zero value otherwise.
func (o *QueueStatsResponse) GetProcessingItems() int32 {
	if o == nil || IsNil(o.ProcessingItems) {
		var ret int32
		return ret
	}
	return *o.ProcessingItems
}

// GetProcessingItemsOk returns a tuple with the ProcessingItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueStatsResponse) GetProcessingItemsOk() (*int32, bool) {
	if o == nil || IsNil(o.ProcessingItems) {
		return nil, false
	}
	return o.ProcessingItems, true
}

// HasProcessingItems returns a boolean if a field has been set.
func (o *QueueStatsResponse) HasProcessingItems() bool {
	if o != nil && !IsNil(o.ProcessingItems) {
		return true
	}

	return false
}

// SetProcessingItems gets a reference to the given int32 and assigns it to the ProcessingItems field.
func (o *QueueStatsResponse) SetProcessingItems(v int32) {
	o.ProcessingItems = &v
}

// GetCompletedItems returns the CompletedItems field value if set, zero value otherwise.
func (o *QueueStatsResponse) GetCompletedItems() int32 {
	if o == nil || IsNil(o.CompletedItems) {
		var ret int32
		return ret
	}
	return *o.CompletedItems
}

// GetCompletedItemsOk returns a tuple with the CompletedItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueStatsResponse) GetCompletedItemsOk() (*int32, bool) {
	if o == nil || IsNil(o.CompletedItems) {
		return nil, false
	}
	return o.CompletedItems, true
}

// HasCompletedItems returns a boolean if a field has been set.
func (o *QueueStatsResponse) HasCompletedItems() bool {
	if o != nil && !IsNil(o.CompletedItems) {
		return true
	}

	return false
}

// SetCompletedItems gets a reference to the given int32 and assigns it to the CompletedItems field.
func (o *QueueStatsResponse) SetCompletedItems(v int32) {
	o.CompletedItems = &v
}

// GetFailedItems returns the FailedItems field value if set, zero value otherwise.
func (o *QueueStatsResponse) GetFailedItems() int32 {
	if o == nil || IsNil(o.FailedItems) {
		var ret int32
		return ret
	}
	return *o.FailedItems
}

// GetFailedItemsOk returns a tuple with the FailedItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueStatsResponse) GetFailedItemsOk() (*int32, bool) {
	if o == nil || IsNil(o.FailedItems) {
		return nil, false
	}
	return o.FailedItems, true
}

// HasFailedItems returns a boolean if a field has been set.
func (o *QueueStatsResponse) HasFailedItems() bool {
	if o != nil && !IsNil(o.FailedItems) {
		return true
	}

	return false
}

// SetFailedItems gets a reference to the given int32 and assigns it to the FailedItems field.
func (o *QueueStatsResponse) SetFailedItems(v int32) {
	o.FailedItems = &v
}

// GetAverageProcessingTime returns the AverageProcessingTime field value if set, zero value otherwise.
func (o *QueueStatsResponse) GetAverageProcessingTime() float32 {
	if o == nil || IsNil(o.AverageProcessingTime) {
		var ret float32
		return ret
	}
	return *o.AverageProcessingTime
}

// GetAverageProcessingTimeOk returns a tuple with the AverageProcessingTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueStatsResponse) GetAverageProcessingTimeOk() (*float32, bool) {
	if o == nil || IsNil(o.AverageProcessingTime) {
		return nil, false
	}
	return o.AverageProcessingTime, true
}

// HasAverageProcessingTime returns a boolean if a field has been set.
func (o *QueueStatsResponse) HasAverageProcessingTime() bool {
	if o != nil && !IsNil(o.AverageProcessingTime) {
		return true
	}

	return false
}

// SetAverageProcessingTime gets a reference to the given float32 and assigns it to the AverageProcessingTime field.
func (o *QueueStatsResponse) SetAverageProcessingTime(v float32) {
	o.AverageProcessingTime = &v
}

// GetThroughput returns the Throughput field value if set, zero value otherwise.
func (o *QueueStatsResponse) GetThroughput() float32 {
	if o == nil || IsNil(o.Throughput) {
		var ret float32
		return ret
	}
	return *o.Throughput
}

// GetThroughputOk returns a tuple with the Throughput field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueStatsResponse) GetThroughputOk() (*float32, bool) {
	if o == nil || IsNil(o.Throughput) {
		return nil, false
	}
	return o.Throughput, true
}

// HasThroughput returns a boolean if a field has been set.
func (o *QueueStatsResponse) HasThroughput() bool {
	if o != nil && !IsNil(o.Throughput) {
		return true
	}

	return false
}

// SetThroughput gets a reference to the given float32 and assigns it to the Throughput field.
func (o *QueueStatsResponse) SetThroughput(v float32) {
	o.Throughput = &v
}

func (o QueueStatsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueueStatsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.TotalItems) {
		toSerialize["totalItems"] = o.TotalItems
	}
	if !IsNil(o.PendingItems) {
		toSerialize["pendingItems"] = o.PendingItems
	}
	if !IsNil(o.ProcessingItems) {
		toSerialize["processingItems"] = o.ProcessingItems
	}
	if !IsNil(o.CompletedItems) {
		toSerialize["completedItems"] = o.CompletedItems
	}
	if !IsNil(o.FailedItems) {
		toSerialize["failedItems"] = o.FailedItems
	}
	if !IsNil(o.AverageProcessingTime) {
		toSerialize["averageProcessingTime"] = o.AverageProcessingTime
	}
	if !IsNil(o.Throughput) {
		toSerialize["throughput"] = o.Throughput
	}
	return toSerialize, nil
}

type NullableQueueStatsResponse struct {
	value *QueueStatsResponse
	isSet bool
}

func (v NullableQueueStatsResponse) Get() *QueueStatsResponse {
	return v.value
}

func (v *NullableQueueStatsResponse) Set(val *QueueStatsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableQueueStatsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableQueueStatsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueueStatsResponse(val *QueueStatsResponse) *NullableQueueStatsResponse {
	return &NullableQueueStatsResponse{value: val, isSet: true}
}

func (v NullableQueueStatsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueueStatsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


