/*
Teams Notification API (Go implementation)

This specification documents the REST endpoints implemented in the Teams Notification Go service. Includes all available routes for internal and external APIs.  ## API Structure - **External APIs** (`/api/v1`): Public APIs for external clients - **Internal APIs** (`/internal/v1`): Internal management APIs - **System APIs**: Health, metrics, and configuration endpoints  ## Recent Updates (v1.0.0) - **Unified Configuration**: Environment-based configuration system - **Error Handling**: Standardized error responses with proper HTTP status codes - **Token Management**: Redis-backed token caching for improved performance - **Monitoring**: Enhanced health checks and system metrics - **Logging**: Structured logging with configurable levels and formats 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package teamsnotify

import (
	"encoding/json"
)

// checks if the NotificationDateRangeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotificationDateRangeResponse{}

// NotificationDateRangeResponse struct for NotificationDateRangeResponse
type NotificationDateRangeResponse struct {
	Data []NotificationResponse `json:"data,omitempty"`
	Count *int32 `json:"count,omitempty"`
	DateRange *NotificationDateRangeResponseDateRange `json:"date_range,omitempty"`
}

// NewNotificationDateRangeResponse instantiates a new NotificationDateRangeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotificationDateRangeResponse() *NotificationDateRangeResponse {
	this := NotificationDateRangeResponse{}
	return &this
}

// NewNotificationDateRangeResponseWithDefaults instantiates a new NotificationDateRangeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotificationDateRangeResponseWithDefaults() *NotificationDateRangeResponse {
	this := NotificationDateRangeResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *NotificationDateRangeResponse) GetData() []NotificationResponse {
	if o == nil || IsNil(o.Data) {
		var ret []NotificationResponse
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationDateRangeResponse) GetDataOk() ([]NotificationResponse, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *NotificationDateRangeResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []NotificationResponse and assigns it to the Data field.
func (o *NotificationDateRangeResponse) SetData(v []NotificationResponse) {
	o.Data = v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *NotificationDateRangeResponse) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationDateRangeResponse) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *NotificationDateRangeResponse) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *NotificationDateRangeResponse) SetCount(v int32) {
	o.Count = &v
}

// GetDateRange returns the DateRange field value if set, zero value otherwise.
func (o *NotificationDateRangeResponse) GetDateRange() NotificationDateRangeResponseDateRange {
	if o == nil || IsNil(o.DateRange) {
		var ret NotificationDateRangeResponseDateRange
		return ret
	}
	return *o.DateRange
}

// GetDateRangeOk returns a tuple with the DateRange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationDateRangeResponse) GetDateRangeOk() (*NotificationDateRangeResponseDateRange, bool) {
	if o == nil || IsNil(o.DateRange) {
		return nil, false
	}
	return o.DateRange, true
}

// HasDateRange returns a boolean if a field has been set.
func (o *NotificationDateRangeResponse) HasDateRange() bool {
	if o != nil && !IsNil(o.DateRange) {
		return true
	}

	return false
}

// SetDateRange gets a reference to the given NotificationDateRangeResponseDateRange and assigns it to the DateRange field.
func (o *NotificationDateRangeResponse) SetDateRange(v NotificationDateRangeResponseDateRange) {
	o.DateRange = &v
}

func (o NotificationDateRangeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotificationDateRangeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.DateRange) {
		toSerialize["date_range"] = o.DateRange
	}
	return toSerialize, nil
}

type NullableNotificationDateRangeResponse struct {
	value *NotificationDateRangeResponse
	isSet bool
}

func (v NullableNotificationDateRangeResponse) Get() *NotificationDateRangeResponse {
	return v.value
}

func (v *NullableNotificationDateRangeResponse) Set(val *NotificationDateRangeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationDateRangeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationDateRangeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationDateRangeResponse(val *NotificationDateRangeResponse) *NullableNotificationDateRangeResponse {
	return &NullableNotificationDateRangeResponse{value: val, isSet: true}
}

func (v NullableNotificationDateRangeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationDateRangeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


