/*
Teams Notification API (Go implementation)

This specification documents the REST endpoints implemented in the Teams Notification Go service. Includes all available routes for internal and external APIs.  ## API Structure - **External APIs** (`/api/v1`): Public APIs for external clients - **Internal APIs** (`/internal/v1`): Internal management APIs - **System APIs**: Health, metrics, and configuration endpoints  ## Recent Updates (v1.0.0) - **Unified Configuration**: Environment-based configuration system - **Error Handling**: Standardized error responses with proper HTTP status codes - **Token Management**: Redis-backed token caching for improved performance - **Monitoring**: Enhanced health checks and system metrics - **Logging**: Structured logging with configurable levels and formats 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package teamsnotify

import (
	"encoding/json"
)

// checks if the AlertsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlertsResponse{}

// AlertsResponse struct for AlertsResponse
type AlertsResponse struct {
	Alerts []AlertsResponseAlertsInner `json:"alerts,omitempty"`
	TotalAlerts *int32 `json:"totalAlerts,omitempty"`
	CriticalAlerts *int32 `json:"criticalAlerts,omitempty"`
}

// NewAlertsResponse instantiates a new AlertsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlertsResponse() *AlertsResponse {
	this := AlertsResponse{}
	return &this
}

// NewAlertsResponseWithDefaults instantiates a new AlertsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertsResponseWithDefaults() *AlertsResponse {
	this := AlertsResponse{}
	return &this
}

// GetAlerts returns the Alerts field value if set, zero value otherwise.
func (o *AlertsResponse) GetAlerts() []AlertsResponseAlertsInner {
	if o == nil || IsNil(o.Alerts) {
		var ret []AlertsResponseAlertsInner
		return ret
	}
	return o.Alerts
}

// GetAlertsOk returns a tuple with the Alerts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertsResponse) GetAlertsOk() ([]AlertsResponseAlertsInner, bool) {
	if o == nil || IsNil(o.Alerts) {
		return nil, false
	}
	return o.Alerts, true
}

// HasAlerts returns a boolean if a field has been set.
func (o *AlertsResponse) HasAlerts() bool {
	if o != nil && !IsNil(o.Alerts) {
		return true
	}

	return false
}

// SetAlerts gets a reference to the given []AlertsResponseAlertsInner and assigns it to the Alerts field.
func (o *AlertsResponse) SetAlerts(v []AlertsResponseAlertsInner) {
	o.Alerts = v
}

// GetTotalAlerts returns the TotalAlerts field value if set, zero value otherwise.
func (o *AlertsResponse) GetTotalAlerts() int32 {
	if o == nil || IsNil(o.TotalAlerts) {
		var ret int32
		return ret
	}
	return *o.TotalAlerts
}

// GetTotalAlertsOk returns a tuple with the TotalAlerts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertsResponse) GetTotalAlertsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalAlerts) {
		return nil, false
	}
	return o.TotalAlerts, true
}

// HasTotalAlerts returns a boolean if a field has been set.
func (o *AlertsResponse) HasTotalAlerts() bool {
	if o != nil && !IsNil(o.TotalAlerts) {
		return true
	}

	return false
}

// SetTotalAlerts gets a reference to the given int32 and assigns it to the TotalAlerts field.
func (o *AlertsResponse) SetTotalAlerts(v int32) {
	o.TotalAlerts = &v
}

// GetCriticalAlerts returns the CriticalAlerts field value if set, zero value otherwise.
func (o *AlertsResponse) GetCriticalAlerts() int32 {
	if o == nil || IsNil(o.CriticalAlerts) {
		var ret int32
		return ret
	}
	return *o.CriticalAlerts
}

// GetCriticalAlertsOk returns a tuple with the CriticalAlerts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertsResponse) GetCriticalAlertsOk() (*int32, bool) {
	if o == nil || IsNil(o.CriticalAlerts) {
		return nil, false
	}
	return o.CriticalAlerts, true
}

// HasCriticalAlerts returns a boolean if a field has been set.
func (o *AlertsResponse) HasCriticalAlerts() bool {
	if o != nil && !IsNil(o.CriticalAlerts) {
		return true
	}

	return false
}

// SetCriticalAlerts gets a reference to the given int32 and assigns it to the CriticalAlerts field.
func (o *AlertsResponse) SetCriticalAlerts(v int32) {
	o.CriticalAlerts = &v
}

func (o AlertsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlertsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Alerts) {
		toSerialize["alerts"] = o.Alerts
	}
	if !IsNil(o.TotalAlerts) {
		toSerialize["totalAlerts"] = o.TotalAlerts
	}
	if !IsNil(o.CriticalAlerts) {
		toSerialize["criticalAlerts"] = o.CriticalAlerts
	}
	return toSerialize, nil
}

type NullableAlertsResponse struct {
	value *AlertsResponse
	isSet bool
}

func (v NullableAlertsResponse) Get() *AlertsResponse {
	return v.value
}

func (v *NullableAlertsResponse) Set(val *AlertsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertsResponse(val *AlertsResponse) *NullableAlertsResponse {
	return &NullableAlertsResponse{value: val, isSet: true}
}

func (v NullableAlertsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


