/*
Teams Notification API (Go implementation)

This specification documents the REST endpoints implemented in the Teams Notification Go service. Includes all available routes for internal and external APIs.  ## API Structure - **External APIs** (`/api/v1`): Public APIs for external clients - **Internal APIs** (`/internal/v1`): Internal management APIs - **System APIs**: Health, metrics, and configuration endpoints  ## Recent Updates (v1.0.0) - **Unified Configuration**: Environment-based configuration system - **Error Handling**: Standardized error responses with proper HTTP status codes - **Token Management**: Redis-backed token caching for improved performance - **Monitoring**: Enhanced health checks and system metrics - **Logging**: Structured logging with configurable levels and formats 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package teamsnotify

import (
	"encoding/json"
	"time"
)

// checks if the QueueStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueueStatusResponse{}

// QueueStatusResponse struct for QueueStatusResponse
type QueueStatusResponse struct {
	Status *string `json:"status,omitempty"`
	Workers *int32 `json:"workers,omitempty"`
	ActiveWorkers *int32 `json:"activeWorkers,omitempty"`
	QueueSize *int32 `json:"queueSize,omitempty"`
	LastProcessed *time.Time `json:"lastProcessed,omitempty"`
}

// NewQueueStatusResponse instantiates a new QueueStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueueStatusResponse() *QueueStatusResponse {
	this := QueueStatusResponse{}
	return &this
}

// NewQueueStatusResponseWithDefaults instantiates a new QueueStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueueStatusResponseWithDefaults() *QueueStatusResponse {
	this := QueueStatusResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *QueueStatusResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueStatusResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *QueueStatusResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *QueueStatusResponse) SetStatus(v string) {
	o.Status = &v
}

// GetWorkers returns the Workers field value if set, zero value otherwise.
func (o *QueueStatusResponse) GetWorkers() int32 {
	if o == nil || IsNil(o.Workers) {
		var ret int32
		return ret
	}
	return *o.Workers
}

// GetWorkersOk returns a tuple with the Workers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueStatusResponse) GetWorkersOk() (*int32, bool) {
	if o == nil || IsNil(o.Workers) {
		return nil, false
	}
	return o.Workers, true
}

// HasWorkers returns a boolean if a field has been set.
func (o *QueueStatusResponse) HasWorkers() bool {
	if o != nil && !IsNil(o.Workers) {
		return true
	}

	return false
}

// SetWorkers gets a reference to the given int32 and assigns it to the Workers field.
func (o *QueueStatusResponse) SetWorkers(v int32) {
	o.Workers = &v
}

// GetActiveWorkers returns the ActiveWorkers field value if set, zero value otherwise.
func (o *QueueStatusResponse) GetActiveWorkers() int32 {
	if o == nil || IsNil(o.ActiveWorkers) {
		var ret int32
		return ret
	}
	return *o.ActiveWorkers
}

// GetActiveWorkersOk returns a tuple with the ActiveWorkers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueStatusResponse) GetActiveWorkersOk() (*int32, bool) {
	if o == nil || IsNil(o.ActiveWorkers) {
		return nil, false
	}
	return o.ActiveWorkers, true
}

// HasActiveWorkers returns a boolean if a field has been set.
func (o *QueueStatusResponse) HasActiveWorkers() bool {
	if o != nil && !IsNil(o.ActiveWorkers) {
		return true
	}

	return false
}

// SetActiveWorkers gets a reference to the given int32 and assigns it to the ActiveWorkers field.
func (o *QueueStatusResponse) SetActiveWorkers(v int32) {
	o.ActiveWorkers = &v
}

// GetQueueSize returns the QueueSize field value if set, zero value otherwise.
func (o *QueueStatusResponse) GetQueueSize() int32 {
	if o == nil || IsNil(o.QueueSize) {
		var ret int32
		return ret
	}
	return *o.QueueSize
}

// GetQueueSizeOk returns a tuple with the QueueSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueStatusResponse) GetQueueSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.QueueSize) {
		return nil, false
	}
	return o.QueueSize, true
}

// HasQueueSize returns a boolean if a field has been set.
func (o *QueueStatusResponse) HasQueueSize() bool {
	if o != nil && !IsNil(o.QueueSize) {
		return true
	}

	return false
}

// SetQueueSize gets a reference to the given int32 and assigns it to the QueueSize field.
func (o *QueueStatusResponse) SetQueueSize(v int32) {
	o.QueueSize = &v
}

// GetLastProcessed returns the LastProcessed field value if set, zero value otherwise.
func (o *QueueStatusResponse) GetLastProcessed() time.Time {
	if o == nil || IsNil(o.LastProcessed) {
		var ret time.Time
		return ret
	}
	return *o.LastProcessed
}

// GetLastProcessedOk returns a tuple with the LastProcessed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueStatusResponse) GetLastProcessedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastProcessed) {
		return nil, false
	}
	return o.LastProcessed, true
}

// HasLastProcessed returns a boolean if a field has been set.
func (o *QueueStatusResponse) HasLastProcessed() bool {
	if o != nil && !IsNil(o.LastProcessed) {
		return true
	}

	return false
}

// SetLastProcessed gets a reference to the given time.Time and assigns it to the LastProcessed field.
func (o *QueueStatusResponse) SetLastProcessed(v time.Time) {
	o.LastProcessed = &v
}

func (o QueueStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueueStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Workers) {
		toSerialize["workers"] = o.Workers
	}
	if !IsNil(o.ActiveWorkers) {
		toSerialize["activeWorkers"] = o.ActiveWorkers
	}
	if !IsNil(o.QueueSize) {
		toSerialize["queueSize"] = o.QueueSize
	}
	if !IsNil(o.LastProcessed) {
		toSerialize["lastProcessed"] = o.LastProcessed
	}
	return toSerialize, nil
}

type NullableQueueStatusResponse struct {
	value *QueueStatusResponse
	isSet bool
}

func (v NullableQueueStatusResponse) Get() *QueueStatusResponse {
	return v.value
}

func (v *NullableQueueStatusResponse) Set(val *QueueStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableQueueStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableQueueStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueueStatusResponse(val *QueueStatusResponse) *NullableQueueStatusResponse {
	return &NullableQueueStatusResponse{value: val, isSet: true}
}

func (v NullableQueueStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueueStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


