/*
Teams Notification API (Go implementation)

Testing InternalAPIProjectsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package teamsnotify

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_teamsnotify_InternalAPIProjectsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test InternalAPIProjectsAPIService InternalV1ProjectsCompanyCompanyIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string

		resp, httpRes, err := apiClient.InternalAPIProjectsAPI.InternalV1ProjectsCompanyCompanyIdGet(context.Background(), companyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InternalAPIProjectsAPIService InternalV1ProjectsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InternalAPIProjectsAPI.InternalV1ProjectsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InternalAPIProjectsAPIService InternalV1ProjectsIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.InternalAPIProjectsAPI.InternalV1ProjectsIdDelete(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InternalAPIProjectsAPIService InternalV1ProjectsIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.InternalAPIProjectsAPI.InternalV1ProjectsIdGet(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InternalAPIProjectsAPIService InternalV1ProjectsIdLimitsPatch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.InternalAPIProjectsAPI.InternalV1ProjectsIdLimitsPatch(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InternalAPIProjectsAPIService InternalV1ProjectsIdPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.InternalAPIProjectsAPI.InternalV1ProjectsIdPut(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InternalAPIProjectsAPIService InternalV1ProjectsKeyKeyNameGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyName string

		resp, httpRes, err := apiClient.InternalAPIProjectsAPI.InternalV1ProjectsKeyKeyNameGet(context.Background(), keyName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InternalAPIProjectsAPIService InternalV1ProjectsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InternalAPIProjectsAPI.InternalV1ProjectsPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
