/*
 * Teams Notification API (Go implementation)
 * This specification documents the REST endpoints implemented in the Teams Notification Go service. Includes all available routes for internal and external APIs.  ## API Structure - **External APIs** (`/api/v1`): Public APIs for external clients - **Internal APIs** (`/internal/v1`): Internal management APIs - **System APIs**: Health, metrics, and configuration endpoints  ## Recent Updates (v1.0.0) - **Unified Configuration**: Environment-based configuration system - **Error Handling**: Standardized error responses with proper HTTP status codes - **Token Management**: Redis-backed token caching for improved performance - **Monitoring**: Enhanced health checks and system metrics - **Logging**: Structured logging with configurable levels and formats 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.BotCapabilitiesUpdateRequest;
import org.openapitools.client.model.BotCreateRequest;
import org.openapitools.client.model.BotListResponse;
import org.openapitools.client.model.BotResponse;
import org.openapitools.client.model.BotStatusUpdateRequest;
import org.openapitools.client.model.BotTestResponse;
import org.openapitools.client.model.BotUpdateRequest;
import org.openapitools.client.model.ErrorResponse;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class InternalApiBotsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public InternalApiBotsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public InternalApiBotsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for internalV1BotsPlatformGet
     * @param limit Number of items to return (optional, default to 10)
     * @param offset Number of items to skip (optional, default to 0)
     * @param search Search term (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of Teams bots </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call internalV1BotsPlatformGetCall(@javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable String search, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/internal/v1/bots/platform";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (offset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offset", offset));
        }

        if (search != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("search", search));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call internalV1BotsPlatformGetValidateBeforeCall(@javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable String search, final ApiCallback _callback) throws ApiException {
        return internalV1BotsPlatformGetCall(limit, offset, search, _callback);

    }

    /**
     * List Teams bots
     * Get a list of Teams bot services
     * @param limit Number of items to return (optional, default to 10)
     * @param offset Number of items to skip (optional, default to 0)
     * @param search Search term (optional)
     * @return BotListResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of Teams bots </td><td>  -  </td></tr>
     </table>
     */
    public BotListResponse internalV1BotsPlatformGet(@javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable String search) throws ApiException {
        ApiResponse<BotListResponse> localVarResp = internalV1BotsPlatformGetWithHttpInfo(limit, offset, search);
        return localVarResp.getData();
    }

    /**
     * List Teams bots
     * Get a list of Teams bot services
     * @param limit Number of items to return (optional, default to 10)
     * @param offset Number of items to skip (optional, default to 0)
     * @param search Search term (optional)
     * @return ApiResponse&lt;BotListResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of Teams bots </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BotListResponse> internalV1BotsPlatformGetWithHttpInfo(@javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable String search) throws ApiException {
        okhttp3.Call localVarCall = internalV1BotsPlatformGetValidateBeforeCall(limit, offset, search, null);
        Type localVarReturnType = new TypeToken<BotListResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List Teams bots (asynchronously)
     * Get a list of Teams bot services
     * @param limit Number of items to return (optional, default to 10)
     * @param offset Number of items to skip (optional, default to 0)
     * @param search Search term (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of Teams bots </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call internalV1BotsPlatformGetAsync(@javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable String search, final ApiCallback<BotListResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = internalV1BotsPlatformGetValidateBeforeCall(limit, offset, search, _callback);
        Type localVarReturnType = new TypeToken<BotListResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for internalV1BotsPlatformIdCapabilitiesPatch
     * @param id  (required)
     * @param botCapabilitiesUpdateRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Bot capabilities updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call internalV1BotsPlatformIdCapabilitiesPatchCall(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull BotCapabilitiesUpdateRequest botCapabilitiesUpdateRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = botCapabilitiesUpdateRequest;

        // create path and map variables
        String localVarPath = "/internal/v1/bots/platform/{id}/capabilities"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call internalV1BotsPlatformIdCapabilitiesPatchValidateBeforeCall(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull BotCapabilitiesUpdateRequest botCapabilitiesUpdateRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling internalV1BotsPlatformIdCapabilitiesPatch(Async)");
        }

        // verify the required parameter 'botCapabilitiesUpdateRequest' is set
        if (botCapabilitiesUpdateRequest == null) {
            throw new ApiException("Missing the required parameter 'botCapabilitiesUpdateRequest' when calling internalV1BotsPlatformIdCapabilitiesPatch(Async)");
        }

        return internalV1BotsPlatformIdCapabilitiesPatchCall(id, botCapabilitiesUpdateRequest, _callback);

    }

    /**
     * Update bot capabilities
     * Update bot capabilities by ID
     * @param id  (required)
     * @param botCapabilitiesUpdateRequest  (required)
     * @return BotResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Bot capabilities updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public BotResponse internalV1BotsPlatformIdCapabilitiesPatch(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull BotCapabilitiesUpdateRequest botCapabilitiesUpdateRequest) throws ApiException {
        ApiResponse<BotResponse> localVarResp = internalV1BotsPlatformIdCapabilitiesPatchWithHttpInfo(id, botCapabilitiesUpdateRequest);
        return localVarResp.getData();
    }

    /**
     * Update bot capabilities
     * Update bot capabilities by ID
     * @param id  (required)
     * @param botCapabilitiesUpdateRequest  (required)
     * @return ApiResponse&lt;BotResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Bot capabilities updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BotResponse> internalV1BotsPlatformIdCapabilitiesPatchWithHttpInfo(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull BotCapabilitiesUpdateRequest botCapabilitiesUpdateRequest) throws ApiException {
        okhttp3.Call localVarCall = internalV1BotsPlatformIdCapabilitiesPatchValidateBeforeCall(id, botCapabilitiesUpdateRequest, null);
        Type localVarReturnType = new TypeToken<BotResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update bot capabilities (asynchronously)
     * Update bot capabilities by ID
     * @param id  (required)
     * @param botCapabilitiesUpdateRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Bot capabilities updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call internalV1BotsPlatformIdCapabilitiesPatchAsync(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull BotCapabilitiesUpdateRequest botCapabilitiesUpdateRequest, final ApiCallback<BotResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = internalV1BotsPlatformIdCapabilitiesPatchValidateBeforeCall(id, botCapabilitiesUpdateRequest, _callback);
        Type localVarReturnType = new TypeToken<BotResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for internalV1BotsPlatformIdDelete
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Bot deleted successfully </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call internalV1BotsPlatformIdDeleteCall(@javax.annotation.Nonnull UUID id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/internal/v1/bots/platform/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call internalV1BotsPlatformIdDeleteValidateBeforeCall(@javax.annotation.Nonnull UUID id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling internalV1BotsPlatformIdDelete(Async)");
        }

        return internalV1BotsPlatformIdDeleteCall(id, _callback);

    }

    /**
     * Delete Teams bot
     * Delete Teams bot by ID
     * @param id  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Bot deleted successfully </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public void internalV1BotsPlatformIdDelete(@javax.annotation.Nonnull UUID id) throws ApiException {
        internalV1BotsPlatformIdDeleteWithHttpInfo(id);
    }

    /**
     * Delete Teams bot
     * Delete Teams bot by ID
     * @param id  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Bot deleted successfully </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> internalV1BotsPlatformIdDeleteWithHttpInfo(@javax.annotation.Nonnull UUID id) throws ApiException {
        okhttp3.Call localVarCall = internalV1BotsPlatformIdDeleteValidateBeforeCall(id, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Delete Teams bot (asynchronously)
     * Delete Teams bot by ID
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Bot deleted successfully </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call internalV1BotsPlatformIdDeleteAsync(@javax.annotation.Nonnull UUID id, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = internalV1BotsPlatformIdDeleteValidateBeforeCall(id, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for internalV1BotsPlatformIdGet
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Bot details </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call internalV1BotsPlatformIdGetCall(@javax.annotation.Nonnull UUID id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/internal/v1/bots/platform/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call internalV1BotsPlatformIdGetValidateBeforeCall(@javax.annotation.Nonnull UUID id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling internalV1BotsPlatformIdGet(Async)");
        }

        return internalV1BotsPlatformIdGetCall(id, _callback);

    }

    /**
     * Get Teams bot
     * Get Teams bot by ID
     * @param id  (required)
     * @return BotResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Bot details </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public BotResponse internalV1BotsPlatformIdGet(@javax.annotation.Nonnull UUID id) throws ApiException {
        ApiResponse<BotResponse> localVarResp = internalV1BotsPlatformIdGetWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Get Teams bot
     * Get Teams bot by ID
     * @param id  (required)
     * @return ApiResponse&lt;BotResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Bot details </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BotResponse> internalV1BotsPlatformIdGetWithHttpInfo(@javax.annotation.Nonnull UUID id) throws ApiException {
        okhttp3.Call localVarCall = internalV1BotsPlatformIdGetValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<BotResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Teams bot (asynchronously)
     * Get Teams bot by ID
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Bot details </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call internalV1BotsPlatformIdGetAsync(@javax.annotation.Nonnull UUID id, final ApiCallback<BotResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = internalV1BotsPlatformIdGetValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<BotResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for internalV1BotsPlatformIdPut
     * @param id  (required)
     * @param botUpdateRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Bot updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call internalV1BotsPlatformIdPutCall(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull BotUpdateRequest botUpdateRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = botUpdateRequest;

        // create path and map variables
        String localVarPath = "/internal/v1/bots/platform/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call internalV1BotsPlatformIdPutValidateBeforeCall(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull BotUpdateRequest botUpdateRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling internalV1BotsPlatformIdPut(Async)");
        }

        // verify the required parameter 'botUpdateRequest' is set
        if (botUpdateRequest == null) {
            throw new ApiException("Missing the required parameter 'botUpdateRequest' when calling internalV1BotsPlatformIdPut(Async)");
        }

        return internalV1BotsPlatformIdPutCall(id, botUpdateRequest, _callback);

    }

    /**
     * Update Teams bot
     * Update Teams bot by ID
     * @param id  (required)
     * @param botUpdateRequest  (required)
     * @return BotResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Bot updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public BotResponse internalV1BotsPlatformIdPut(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull BotUpdateRequest botUpdateRequest) throws ApiException {
        ApiResponse<BotResponse> localVarResp = internalV1BotsPlatformIdPutWithHttpInfo(id, botUpdateRequest);
        return localVarResp.getData();
    }

    /**
     * Update Teams bot
     * Update Teams bot by ID
     * @param id  (required)
     * @param botUpdateRequest  (required)
     * @return ApiResponse&lt;BotResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Bot updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BotResponse> internalV1BotsPlatformIdPutWithHttpInfo(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull BotUpdateRequest botUpdateRequest) throws ApiException {
        okhttp3.Call localVarCall = internalV1BotsPlatformIdPutValidateBeforeCall(id, botUpdateRequest, null);
        Type localVarReturnType = new TypeToken<BotResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update Teams bot (asynchronously)
     * Update Teams bot by ID
     * @param id  (required)
     * @param botUpdateRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Bot updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call internalV1BotsPlatformIdPutAsync(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull BotUpdateRequest botUpdateRequest, final ApiCallback<BotResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = internalV1BotsPlatformIdPutValidateBeforeCall(id, botUpdateRequest, _callback);
        Type localVarReturnType = new TypeToken<BotResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for internalV1BotsPlatformIdStatusPatch
     * @param id  (required)
     * @param botStatusUpdateRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Bot status updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call internalV1BotsPlatformIdStatusPatchCall(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull BotStatusUpdateRequest botStatusUpdateRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = botStatusUpdateRequest;

        // create path and map variables
        String localVarPath = "/internal/v1/bots/platform/{id}/status"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call internalV1BotsPlatformIdStatusPatchValidateBeforeCall(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull BotStatusUpdateRequest botStatusUpdateRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling internalV1BotsPlatformIdStatusPatch(Async)");
        }

        // verify the required parameter 'botStatusUpdateRequest' is set
        if (botStatusUpdateRequest == null) {
            throw new ApiException("Missing the required parameter 'botStatusUpdateRequest' when calling internalV1BotsPlatformIdStatusPatch(Async)");
        }

        return internalV1BotsPlatformIdStatusPatchCall(id, botStatusUpdateRequest, _callback);

    }

    /**
     * Update bot status
     * Update bot status by ID
     * @param id  (required)
     * @param botStatusUpdateRequest  (required)
     * @return BotResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Bot status updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public BotResponse internalV1BotsPlatformIdStatusPatch(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull BotStatusUpdateRequest botStatusUpdateRequest) throws ApiException {
        ApiResponse<BotResponse> localVarResp = internalV1BotsPlatformIdStatusPatchWithHttpInfo(id, botStatusUpdateRequest);
        return localVarResp.getData();
    }

    /**
     * Update bot status
     * Update bot status by ID
     * @param id  (required)
     * @param botStatusUpdateRequest  (required)
     * @return ApiResponse&lt;BotResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Bot status updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BotResponse> internalV1BotsPlatformIdStatusPatchWithHttpInfo(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull BotStatusUpdateRequest botStatusUpdateRequest) throws ApiException {
        okhttp3.Call localVarCall = internalV1BotsPlatformIdStatusPatchValidateBeforeCall(id, botStatusUpdateRequest, null);
        Type localVarReturnType = new TypeToken<BotResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update bot status (asynchronously)
     * Update bot status by ID
     * @param id  (required)
     * @param botStatusUpdateRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Bot status updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call internalV1BotsPlatformIdStatusPatchAsync(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull BotStatusUpdateRequest botStatusUpdateRequest, final ApiCallback<BotResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = internalV1BotsPlatformIdStatusPatchValidateBeforeCall(id, botStatusUpdateRequest, _callback);
        Type localVarReturnType = new TypeToken<BotResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for internalV1BotsPlatformIdTestPost
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Bot connection test result </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call internalV1BotsPlatformIdTestPostCall(@javax.annotation.Nonnull UUID id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/internal/v1/bots/platform/{id}/test"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call internalV1BotsPlatformIdTestPostValidateBeforeCall(@javax.annotation.Nonnull UUID id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling internalV1BotsPlatformIdTestPost(Async)");
        }

        return internalV1BotsPlatformIdTestPostCall(id, _callback);

    }

    /**
     * Test bot connection
     * Test bot connection by ID
     * @param id  (required)
     * @return BotTestResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Bot connection test result </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public BotTestResponse internalV1BotsPlatformIdTestPost(@javax.annotation.Nonnull UUID id) throws ApiException {
        ApiResponse<BotTestResponse> localVarResp = internalV1BotsPlatformIdTestPostWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Test bot connection
     * Test bot connection by ID
     * @param id  (required)
     * @return ApiResponse&lt;BotTestResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Bot connection test result </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BotTestResponse> internalV1BotsPlatformIdTestPostWithHttpInfo(@javax.annotation.Nonnull UUID id) throws ApiException {
        okhttp3.Call localVarCall = internalV1BotsPlatformIdTestPostValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<BotTestResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Test bot connection (asynchronously)
     * Test bot connection by ID
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Bot connection test result </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call internalV1BotsPlatformIdTestPostAsync(@javax.annotation.Nonnull UUID id, final ApiCallback<BotTestResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = internalV1BotsPlatformIdTestPostValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<BotTestResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for internalV1BotsPlatformPost
     * @param botCreateRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Bot created successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call internalV1BotsPlatformPostCall(@javax.annotation.Nonnull BotCreateRequest botCreateRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = botCreateRequest;

        // create path and map variables
        String localVarPath = "/internal/v1/bots/platform";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call internalV1BotsPlatformPostValidateBeforeCall(@javax.annotation.Nonnull BotCreateRequest botCreateRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'botCreateRequest' is set
        if (botCreateRequest == null) {
            throw new ApiException("Missing the required parameter 'botCreateRequest' when calling internalV1BotsPlatformPost(Async)");
        }

        return internalV1BotsPlatformPostCall(botCreateRequest, _callback);

    }

    /**
     * Create Teams bot
     * Create a new Teams bot service
     * @param botCreateRequest  (required)
     * @return BotResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Bot created successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
     </table>
     */
    public BotResponse internalV1BotsPlatformPost(@javax.annotation.Nonnull BotCreateRequest botCreateRequest) throws ApiException {
        ApiResponse<BotResponse> localVarResp = internalV1BotsPlatformPostWithHttpInfo(botCreateRequest);
        return localVarResp.getData();
    }

    /**
     * Create Teams bot
     * Create a new Teams bot service
     * @param botCreateRequest  (required)
     * @return ApiResponse&lt;BotResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Bot created successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BotResponse> internalV1BotsPlatformPostWithHttpInfo(@javax.annotation.Nonnull BotCreateRequest botCreateRequest) throws ApiException {
        okhttp3.Call localVarCall = internalV1BotsPlatformPostValidateBeforeCall(botCreateRequest, null);
        Type localVarReturnType = new TypeToken<BotResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create Teams bot (asynchronously)
     * Create a new Teams bot service
     * @param botCreateRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Bot created successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call internalV1BotsPlatformPostAsync(@javax.annotation.Nonnull BotCreateRequest botCreateRequest, final ApiCallback<BotResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = internalV1BotsPlatformPostValidateBeforeCall(botCreateRequest, _callback);
        Type localVarReturnType = new TypeToken<BotResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for internalV1BotsStatusStatusGet
     * @param status  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of bots with status </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call internalV1BotsStatusStatusGetCall(@javax.annotation.Nonnull String status, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/internal/v1/bots/status/{status}"
            .replace("{" + "status" + "}", localVarApiClient.escapeString(status.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call internalV1BotsStatusStatusGetValidateBeforeCall(@javax.annotation.Nonnull String status, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'status' is set
        if (status == null) {
            throw new ApiException("Missing the required parameter 'status' when calling internalV1BotsStatusStatusGet(Async)");
        }

        return internalV1BotsStatusStatusGetCall(status, _callback);

    }

    /**
     * Get bots by status
     * Get bots by status
     * @param status  (required)
     * @return BotListResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of bots with status </td><td>  -  </td></tr>
     </table>
     */
    public BotListResponse internalV1BotsStatusStatusGet(@javax.annotation.Nonnull String status) throws ApiException {
        ApiResponse<BotListResponse> localVarResp = internalV1BotsStatusStatusGetWithHttpInfo(status);
        return localVarResp.getData();
    }

    /**
     * Get bots by status
     * Get bots by status
     * @param status  (required)
     * @return ApiResponse&lt;BotListResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of bots with status </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BotListResponse> internalV1BotsStatusStatusGetWithHttpInfo(@javax.annotation.Nonnull String status) throws ApiException {
        okhttp3.Call localVarCall = internalV1BotsStatusStatusGetValidateBeforeCall(status, null);
        Type localVarReturnType = new TypeToken<BotListResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get bots by status (asynchronously)
     * Get bots by status
     * @param status  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of bots with status </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call internalV1BotsStatusStatusGetAsync(@javax.annotation.Nonnull String status, final ApiCallback<BotListResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = internalV1BotsStatusStatusGetValidateBeforeCall(status, _callback);
        Type localVarReturnType = new TypeToken<BotListResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
