/*
 * Teams Notification API (Go implementation)
 * This specification documents the REST endpoints implemented in the Teams Notification Go service. Includes all available routes for internal and external APIs.  ## API Structure - **External APIs** (`/api/v1`): Public APIs for external clients - **Internal APIs** (`/internal/v1`): Internal management APIs - **System APIs**: Health, metrics, and configuration endpoints  ## Recent Updates (v1.0.0) - **Unified Configuration**: Environment-based configuration system - **Error Handling**: Standardized error responses with proper HTTP status codes - **Token Management**: Redis-backed token caching for improved performance - **Monitoring**: Enhanced health checks and system metrics - **Logging**: Structured logging with configurable levels and formats 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.BotFrameworkActivity;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.ExternalNotifyRequest;
import org.openapitools.client.model.ExternalNotifyResponse;
import org.openapitools.client.model.MessageResponse;
import org.openapitools.client.model.ProactiveTestRequest;
import org.openapitools.client.model.ProjectDestinationsResponse;
import org.openapitools.client.model.ProvisionCreateRequest;
import org.openapitools.client.model.ProvisionResponse;
import org.openapitools.client.model.ProvisionUpdateRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ExternalApiApi
 */
@Disabled
public class ExternalApiApiTest {

    private final ExternalApiApi api = new ExternalApiApi();

    /**
     * Get project destinations (External API)
     *
     * Get destinations for a project using notify key
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1DestinationsNotifyKeyGetTest() throws ApiException {
        String notifyKey = null;
        ProjectDestinationsResponse response = api.apiV1DestinationsNotifyKeyGet(notifyKey);
        // TODO: test validations
    }

    /**
     * Handle Bot Framework messages
     *
     * Handle incoming Bot Framework Activity messages
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1MessagesPostTest() throws ApiException {
        BotFrameworkActivity botFrameworkActivity = null;
        MessageResponse response = api.apiV1MessagesPost(botFrameworkActivity);
        // TODO: test validations
    }

    /**
     * Test proactive message
     *
     * Send a test proactive message
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1MessagesTestPostTest() throws ApiException {
        ProactiveTestRequest proactiveTestRequest = null;
        MessageResponse response = api.apiV1MessagesTestPost(proactiveTestRequest);
        // TODO: test validations
    }

    /**
     * Send notification (External API)
     *
     * Send a notification to Teams using project notify key
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1NotifyPostTest() throws ApiException {
        ExternalNotifyRequest externalNotifyRequest = null;
        ExternalNotifyResponse response = api.apiV1NotifyPost(externalNotifyRequest);
        // TODO: test validations
    }

    /**
     * Disable project provision
     *
     * Disable project provision by notify key
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1ProvisionNotifyKeyDisablePostTest() throws ApiException {
        String notifyKey = null;
        ProvisionResponse response = api.apiV1ProvisionNotifyKeyDisablePost(notifyKey);
        // TODO: test validations
    }

    /**
     * Enable project provision
     *
     * Enable project provision by notify key
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1ProvisionNotifyKeyEnablePostTest() throws ApiException {
        String notifyKey = null;
        ProvisionResponse response = api.apiV1ProvisionNotifyKeyEnablePost(notifyKey);
        // TODO: test validations
    }

    /**
     * Get project provision
     *
     * Get project provision by notify key
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1ProvisionNotifyKeyGetTest() throws ApiException {
        String notifyKey = null;
        ProvisionResponse response = api.apiV1ProvisionNotifyKeyGet(notifyKey);
        // TODO: test validations
    }

    /**
     * Update project provision
     *
     * Update project provision by notify key
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1ProvisionNotifyKeyPutTest() throws ApiException {
        String notifyKey = null;
        ProvisionUpdateRequest provisionUpdateRequest = null;
        ProvisionResponse response = api.apiV1ProvisionNotifyKeyPut(notifyKey, provisionUpdateRequest);
        // TODO: test validations
    }

    /**
     * Create project provision
     *
     * Create a new project provision
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV1ProvisionPostTest() throws ApiException {
        ProvisionCreateRequest provisionCreateRequest = null;
        ProvisionResponse response = api.apiV1ProvisionPost(provisionCreateRequest);
        // TODO: test validations
    }

}
