/*
 * Teams Notification API (Go implementation)
 * This specification documents the REST endpoints implemented in the Teams Notification Go service. Includes all available routes for internal and external APIs.  ## API Structure - **External APIs** (`/api/v1`): Public APIs for external clients - **Internal APIs** (`/internal/v1`): Internal management APIs - **System APIs**: Health, metrics, and configuration endpoints  ## Recent Updates (v1.0.0) - **Unified Configuration**: Environment-based configuration system - **Error Handling**: Standardized error responses with proper HTTP status codes - **Token Management**: Redis-backed token caching for improved performance - **Monitoring**: Enhanced health checks and system metrics - **Logging**: Structured logging with configurable levels and formats 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.client.model.PerformanceMetricsResponseCpu;
import org.openapitools.client.model.PerformanceMetricsResponseDatabase;
import org.openapitools.client.model.PerformanceMetricsResponseMemory;
import org.openapitools.client.model.PerformanceMetricsResponseRedis;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * PerformanceMetricsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-27T17:29:12.283433+08:00[Asia/Taipei]", comments = "Generator version: 7.16.0")
public class PerformanceMetricsResponse {
  public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP)
  @javax.annotation.Nullable
  private OffsetDateTime timestamp;

  public static final String SERIALIZED_NAME_CPU = "cpu";
  @SerializedName(SERIALIZED_NAME_CPU)
  @javax.annotation.Nullable
  private PerformanceMetricsResponseCpu cpu;

  public static final String SERIALIZED_NAME_MEMORY = "memory";
  @SerializedName(SERIALIZED_NAME_MEMORY)
  @javax.annotation.Nullable
  private PerformanceMetricsResponseMemory memory;

  public static final String SERIALIZED_NAME_DATABASE = "database";
  @SerializedName(SERIALIZED_NAME_DATABASE)
  @javax.annotation.Nullable
  private PerformanceMetricsResponseDatabase database;

  public static final String SERIALIZED_NAME_REDIS = "redis";
  @SerializedName(SERIALIZED_NAME_REDIS)
  @javax.annotation.Nullable
  private PerformanceMetricsResponseRedis redis;

  public PerformanceMetricsResponse() {
  }

  public PerformanceMetricsResponse timestamp(@javax.annotation.Nullable OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Get timestamp
   * @return timestamp
   */
  @javax.annotation.Nullable
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(@javax.annotation.Nullable OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  public PerformanceMetricsResponse cpu(@javax.annotation.Nullable PerformanceMetricsResponseCpu cpu) {
    this.cpu = cpu;
    return this;
  }

  /**
   * Get cpu
   * @return cpu
   */
  @javax.annotation.Nullable
  public PerformanceMetricsResponseCpu getCpu() {
    return cpu;
  }

  public void setCpu(@javax.annotation.Nullable PerformanceMetricsResponseCpu cpu) {
    this.cpu = cpu;
  }


  public PerformanceMetricsResponse memory(@javax.annotation.Nullable PerformanceMetricsResponseMemory memory) {
    this.memory = memory;
    return this;
  }

  /**
   * Get memory
   * @return memory
   */
  @javax.annotation.Nullable
  public PerformanceMetricsResponseMemory getMemory() {
    return memory;
  }

  public void setMemory(@javax.annotation.Nullable PerformanceMetricsResponseMemory memory) {
    this.memory = memory;
  }


  public PerformanceMetricsResponse database(@javax.annotation.Nullable PerformanceMetricsResponseDatabase database) {
    this.database = database;
    return this;
  }

  /**
   * Get database
   * @return database
   */
  @javax.annotation.Nullable
  public PerformanceMetricsResponseDatabase getDatabase() {
    return database;
  }

  public void setDatabase(@javax.annotation.Nullable PerformanceMetricsResponseDatabase database) {
    this.database = database;
  }


  public PerformanceMetricsResponse redis(@javax.annotation.Nullable PerformanceMetricsResponseRedis redis) {
    this.redis = redis;
    return this;
  }

  /**
   * Get redis
   * @return redis
   */
  @javax.annotation.Nullable
  public PerformanceMetricsResponseRedis getRedis() {
    return redis;
  }

  public void setRedis(@javax.annotation.Nullable PerformanceMetricsResponseRedis redis) {
    this.redis = redis;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PerformanceMetricsResponse performanceMetricsResponse = (PerformanceMetricsResponse) o;
    return Objects.equals(this.timestamp, performanceMetricsResponse.timestamp) &&
        Objects.equals(this.cpu, performanceMetricsResponse.cpu) &&
        Objects.equals(this.memory, performanceMetricsResponse.memory) &&
        Objects.equals(this.database, performanceMetricsResponse.database) &&
        Objects.equals(this.redis, performanceMetricsResponse.redis);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timestamp, cpu, memory, database, redis);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PerformanceMetricsResponse {\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    cpu: ").append(toIndentedString(cpu)).append("\n");
    sb.append("    memory: ").append(toIndentedString(memory)).append("\n");
    sb.append("    database: ").append(toIndentedString(database)).append("\n");
    sb.append("    redis: ").append(toIndentedString(redis)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("timestamp", "cpu", "memory", "database", "redis"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PerformanceMetricsResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PerformanceMetricsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in PerformanceMetricsResponse is not found in the empty JSON string", PerformanceMetricsResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PerformanceMetricsResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `PerformanceMetricsResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `cpu`
      if (jsonObj.get("cpu") != null && !jsonObj.get("cpu").isJsonNull()) {
        PerformanceMetricsResponseCpu.validateJsonElement(jsonObj.get("cpu"));
      }
      // validate the optional field `memory`
      if (jsonObj.get("memory") != null && !jsonObj.get("memory").isJsonNull()) {
        PerformanceMetricsResponseMemory.validateJsonElement(jsonObj.get("memory"));
      }
      // validate the optional field `database`
      if (jsonObj.get("database") != null && !jsonObj.get("database").isJsonNull()) {
        PerformanceMetricsResponseDatabase.validateJsonElement(jsonObj.get("database"));
      }
      // validate the optional field `redis`
      if (jsonObj.get("redis") != null && !jsonObj.get("redis").isJsonNull()) {
        PerformanceMetricsResponseRedis.validateJsonElement(jsonObj.get("redis"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PerformanceMetricsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PerformanceMetricsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PerformanceMetricsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PerformanceMetricsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<PerformanceMetricsResponse>() {
           @Override
           public void write(JsonWriter out, PerformanceMetricsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PerformanceMetricsResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PerformanceMetricsResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PerformanceMetricsResponse
   * @throws IOException if the JSON string is invalid with respect to PerformanceMetricsResponse
   */
  public static PerformanceMetricsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PerformanceMetricsResponse.class);
  }

  /**
   * Convert an instance of PerformanceMetricsResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

