/*
 * Teams Notification API (Go implementation)
 * This specification documents the REST endpoints implemented in the Teams Notification Go service. Includes all available routes for internal and external APIs.  ## API Structure - **External APIs** (`/api/v1`): Public APIs for external clients - **Internal APIs** (`/internal/v1`): Internal management APIs - **System APIs**: Health, metrics, and configuration endpoints  ## Recent Updates (v1.0.0) - **Unified Configuration**: Environment-based configuration system - **Error Handling**: Standardized error responses with proper HTTP status codes - **Token Management**: Redis-backed token caching for improved performance - **Monitoring**: Enhanced health checks and system metrics - **Logging**: Structured logging with configurable levels and formats 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * PerformanceMetricsResponseRedis
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-27T17:29:12.283433+08:00[Asia/Taipei]", comments = "Generator version: 7.16.0")
public class PerformanceMetricsResponseRedis {
  public static final String SERIALIZED_NAME_MEMORY = "memory";
  @SerializedName(SERIALIZED_NAME_MEMORY)
  @javax.annotation.Nullable
  private Integer memory;

  public static final String SERIALIZED_NAME_KEYS = "keys";
  @SerializedName(SERIALIZED_NAME_KEYS)
  @javax.annotation.Nullable
  private Integer keys;

  public static final String SERIALIZED_NAME_HIT_RATE = "hitRate";
  @SerializedName(SERIALIZED_NAME_HIT_RATE)
  @javax.annotation.Nullable
  private BigDecimal hitRate;

  public PerformanceMetricsResponseRedis() {
  }

  public PerformanceMetricsResponseRedis memory(@javax.annotation.Nullable Integer memory) {
    this.memory = memory;
    return this;
  }

  /**
   * Get memory
   * @return memory
   */
  @javax.annotation.Nullable
  public Integer getMemory() {
    return memory;
  }

  public void setMemory(@javax.annotation.Nullable Integer memory) {
    this.memory = memory;
  }


  public PerformanceMetricsResponseRedis keys(@javax.annotation.Nullable Integer keys) {
    this.keys = keys;
    return this;
  }

  /**
   * Get keys
   * @return keys
   */
  @javax.annotation.Nullable
  public Integer getKeys() {
    return keys;
  }

  public void setKeys(@javax.annotation.Nullable Integer keys) {
    this.keys = keys;
  }


  public PerformanceMetricsResponseRedis hitRate(@javax.annotation.Nullable BigDecimal hitRate) {
    this.hitRate = hitRate;
    return this;
  }

  /**
   * Get hitRate
   * @return hitRate
   */
  @javax.annotation.Nullable
  public BigDecimal getHitRate() {
    return hitRate;
  }

  public void setHitRate(@javax.annotation.Nullable BigDecimal hitRate) {
    this.hitRate = hitRate;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PerformanceMetricsResponseRedis performanceMetricsResponseRedis = (PerformanceMetricsResponseRedis) o;
    return Objects.equals(this.memory, performanceMetricsResponseRedis.memory) &&
        Objects.equals(this.keys, performanceMetricsResponseRedis.keys) &&
        Objects.equals(this.hitRate, performanceMetricsResponseRedis.hitRate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(memory, keys, hitRate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PerformanceMetricsResponseRedis {\n");
    sb.append("    memory: ").append(toIndentedString(memory)).append("\n");
    sb.append("    keys: ").append(toIndentedString(keys)).append("\n");
    sb.append("    hitRate: ").append(toIndentedString(hitRate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("memory", "keys", "hitRate"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PerformanceMetricsResponseRedis
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PerformanceMetricsResponseRedis.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in PerformanceMetricsResponseRedis is not found in the empty JSON string", PerformanceMetricsResponseRedis.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PerformanceMetricsResponseRedis.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `PerformanceMetricsResponseRedis` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PerformanceMetricsResponseRedis.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PerformanceMetricsResponseRedis' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PerformanceMetricsResponseRedis> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PerformanceMetricsResponseRedis.class));

       return (TypeAdapter<T>) new TypeAdapter<PerformanceMetricsResponseRedis>() {
           @Override
           public void write(JsonWriter out, PerformanceMetricsResponseRedis value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PerformanceMetricsResponseRedis read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PerformanceMetricsResponseRedis given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PerformanceMetricsResponseRedis
   * @throws IOException if the JSON string is invalid with respect to PerformanceMetricsResponseRedis
   */
  public static PerformanceMetricsResponseRedis fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PerformanceMetricsResponseRedis.class);
  }

  /**
   * Convert an instance of PerformanceMetricsResponseRedis to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

