/*
 * Teams Notification API (Go implementation)
 * This specification documents the REST endpoints implemented in the Teams Notification Go service. Includes all available routes for internal and external APIs.  ## API Structure - **External APIs** (`/api/v1`): Public APIs for external clients - **Internal APIs** (`/internal/v1`): Internal management APIs - **System APIs**: Health, metrics, and configuration endpoints  ## Recent Updates (v1.0.0) - **Unified Configuration**: Environment-based configuration system - **Error Handling**: Standardized error responses with proper HTTP status codes - **Token Management**: Redis-backed token caching for improved performance - **Monitoring**: Enhanced health checks and system metrics - **Logging**: Structured logging with configurable levels and formats 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.DestinationResponse;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * ProjectDestinationsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-27T17:29:12.283433+08:00[Asia/Taipei]", comments = "Generator version: 7.16.0")
public class ProjectDestinationsResponse {
  public static final String SERIALIZED_NAME_NOTIFY_KEY = "notifyKey";
  @SerializedName(SERIALIZED_NAME_NOTIFY_KEY)
  @javax.annotation.Nullable
  private String notifyKey;

  public static final String SERIALIZED_NAME_DESTINATIONS = "destinations";
  @SerializedName(SERIALIZED_NAME_DESTINATIONS)
  @javax.annotation.Nullable
  private List<DestinationResponse> destinations = new ArrayList<>();

  public ProjectDestinationsResponse() {
  }

  public ProjectDestinationsResponse notifyKey(@javax.annotation.Nullable String notifyKey) {
    this.notifyKey = notifyKey;
    return this;
  }

  /**
   * Get notifyKey
   * @return notifyKey
   */
  @javax.annotation.Nullable
  public String getNotifyKey() {
    return notifyKey;
  }

  public void setNotifyKey(@javax.annotation.Nullable String notifyKey) {
    this.notifyKey = notifyKey;
  }


  public ProjectDestinationsResponse destinations(@javax.annotation.Nullable List<DestinationResponse> destinations) {
    this.destinations = destinations;
    return this;
  }

  public ProjectDestinationsResponse addDestinationsItem(DestinationResponse destinationsItem) {
    if (this.destinations == null) {
      this.destinations = new ArrayList<>();
    }
    this.destinations.add(destinationsItem);
    return this;
  }

  /**
   * Get destinations
   * @return destinations
   */
  @javax.annotation.Nullable
  public List<DestinationResponse> getDestinations() {
    return destinations;
  }

  public void setDestinations(@javax.annotation.Nullable List<DestinationResponse> destinations) {
    this.destinations = destinations;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectDestinationsResponse projectDestinationsResponse = (ProjectDestinationsResponse) o;
    return Objects.equals(this.notifyKey, projectDestinationsResponse.notifyKey) &&
        Objects.equals(this.destinations, projectDestinationsResponse.destinations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(notifyKey, destinations);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectDestinationsResponse {\n");
    sb.append("    notifyKey: ").append(toIndentedString(notifyKey)).append("\n");
    sb.append("    destinations: ").append(toIndentedString(destinations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("notifyKey", "destinations"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ProjectDestinationsResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ProjectDestinationsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in ProjectDestinationsResponse is not found in the empty JSON string", ProjectDestinationsResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ProjectDestinationsResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ProjectDestinationsResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("notifyKey") != null && !jsonObj.get("notifyKey").isJsonNull()) && !jsonObj.get("notifyKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `notifyKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("notifyKey").toString()));
      }
      if (jsonObj.get("destinations") != null && !jsonObj.get("destinations").isJsonNull()) {
        JsonArray jsonArraydestinations = jsonObj.getAsJsonArray("destinations");
        if (jsonArraydestinations != null) {
          // ensure the json data is an array
          if (!jsonObj.get("destinations").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `destinations` to be an array in the JSON string but got `%s`", jsonObj.get("destinations").toString()));
          }

          // validate the optional field `destinations` (array)
          for (int i = 0; i < jsonArraydestinations.size(); i++) {
            DestinationResponse.validateJsonElement(jsonArraydestinations.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProjectDestinationsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProjectDestinationsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProjectDestinationsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProjectDestinationsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ProjectDestinationsResponse>() {
           @Override
           public void write(JsonWriter out, ProjectDestinationsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ProjectDestinationsResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ProjectDestinationsResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ProjectDestinationsResponse
   * @throws IOException if the JSON string is invalid with respect to ProjectDestinationsResponse
   */
  public static ProjectDestinationsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProjectDestinationsResponse.class);
  }

  /**
   * Convert an instance of ProjectDestinationsResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

